apiVersion: v1
kind: Service
metadata:
  name: sast-agent
  namespace: sast-monitoring
  labels:
    app: sast-agent
spec:
  type: ClusterIP
  selector:
    app: sast-agent
  ports:
    - name: http
      port: 5000
      targetPort: http
